In [ ]:
# SPD Matrix is positive definite matrix is a matrix with all positive eigenvalues. 
# We have 3 matrixes as examples, firstly, we need to check their if their eigenvalues are positive. To do so, we will use np.linalg.eigvals function.

In [45]:
import numpy as np
import math
import sys

In [48]:
A = np.array([[6, 5, -5, -2],
             [5, -7, 6, 5],
             [-5, 6, -9, -6],
             [-2, 5, -6, 0]])

B = np.array([[6, 5, -23, -2], 
             [5, -7, 16, 5],
             [-23, 16, -9, -6],
             [-2, 5, -1, 1]])

C = np.array([[9, -6, 3, 3],
             [-6, 20, -6, 2],
             [3, -6, 18, -4],
             [3, 2, -4, 4]])

np.linalg.eigvals(A), np.linalg.eigvals(B), np.linalg.eigvals(C)

(array([-19.61471516,   8.29037304,   3.27518877,  -1.95084665]),
 array([-35.7883131 ,  23.6988096 ,  -0.66777542,   3.75727892]),
 array([27.75749635,  0.69670695,  8.45514026, 14.09065645]))

In [51]:
def Cholesky_Decomposition(matrix, n):
 
    lower = [[0 for x in range(n + 1)]
                for y in range(n + 1)];
 
    for i in range(n):
        for j in range(i + 1):
            sum1 = 0;
 
            if (j == i):
                for k in range(j):
                    sum1 += pow(lower[j][k], 2);
                lower[j][j] = int(math.sqrt(matrix[j][j] - sum1));
            else:
                 
                for k in range(j):
                    sum1 += (lower[i][k] *lower[j][k]);
                if(lower[j][j] > 0):
                    lower[i][j] = int((matrix[i][j] - sum1) /
                                               lower[j][j]);
 
    print("Lower Triangular\t\tTranspose");
    for i in range(n):
        for j in range(n):
            print(lower[i][j], end = "\t");
        print("", end = "\t");
        for j in range(n):
            print(lower[j][i], end = "\t");
        print("");

Cholesky_Decomposition(C, C.shape[0]);

Lower Triangular		Transpose
3	0	0	0		3	-2	1	1	
-2	4	0	0		0	4	-1	1	
1	-1	4	0		0	0	4	-1	
1	1	-1	1		0	0	0	1	
